apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sappswd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sappswddeployment
  template:
    metadata:
      labels:
        app: k8sappswddeployment
    spec:
      containers:
      - name: k8sappswddeployment
        image: k8sappswd:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
            protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"